# Site settings
title: Angel Milla
description: 'Business Card Page'
url: 'https://angheljf.github.io/'
baseurl: ''
profilepic: '/images/milla.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '6cf5ba588e.js'

author:
  name: 'Angel Milla'
  email: angheljf@gmail.com
  twitter_username: angheljf18
  facebook_username: angel.milla.9
  github_username:  angheljf
  linkedin_username:  angel-milla
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
